added branch check to only allow PRs / merges from dev

diff --git a/.github/workflows/CD-Prod.yml b/.github/workflows/CD-Prod.yml
--- a/.github/workflows/CD-Prod.yml
+++ b/.github/workflows/CD-Prod.yml
@@ -13,6 +13,14 @@ permissions:
   pull-requests: write  # needed if we want to post plan output as PR comment
 
 jobs:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'dev'
+        run: |
+          echo "ERROR: You can only merge to main from dev."
+          exit 1
   plan-prod:
     name: Plan for Prod
     runs-on: ubuntu-latest
